In [1]:
import pandas as pd
import sqlite3

In [2]:
conn = sqlite3.connect(r"C:\Users\odai\Desktop\sqllite\olist.sqlite")

In [ ]:
df = pd.read_sql(
    f"SELECT product_id ,product_category_name ,product_weight_g,product_length_cm ,product_height_cm ,product_width_cm FROM products",
    conn,
)

In [49]:
df.head()

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,625.0,20.0,17.0,13.0

In [50]:
df.isnull().sum()

product_id                 0
product_category_name    610
product_weight_g           2
product_length_cm          2
product_height_cm          2
product_width_cm           2
dtype: int64

In [51]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   product_id             32951 non-null  str
 1   product_category_name  32341 non-null  str
 2   product_weight_g       32949 non-null  float64
 3   product_length_cm      32949 non-null  float64
 4   product_height_cm      32949 non-null  float64
 5   product_width_cm       32949 non-null  float64
dtypes: float64(4), str(2)
memory usage: 1.5 MB

In [ ]:
df["product_category_name"] = df["product_category_name"].fillna(
    "Unknown", inplace=True
)
num_cols = [
    "product_weight_g",
    "product_width_cm",
    "product_height_cm",
    "product_length_cm",
]
df[num_cols] = df[num_cols].fillna(df[num_cols].mean())

C:\Users\odai\AppData\Local\Temp\ipykernel_28860\2909507780.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['product_category_name']=df['product_category_name'].fillna('Unknown', inplace=True)

In [55]:
df.isna().sum()

product_id               0
product_category_name    0
product_weight_g         0
product_length_cm        0
product_height_cm        0
product_width_cm         0
dtype: int64

In [ ]:
from sqlalchemy import create_engine

engine = create_engine("postgresql://postgres:admin@localhost:5432/new-DWH")

with engine.connect() as connection:
    df.to_sql("dimproduct", con=connection, if_exists="append", index=False)

In [ ]:
df_customer = pd.read_sql(
    f"SELECT customer_id,customer_unique_id, customer_city, customer_state from customers",
    conn,
)

In [62]:
df_customer.head()

,customer_id,customer_unique_id,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,campinas,SP

In [63]:
df_customer.isna().sum()

customer_id           0
customer_unique_id    0
customer_city         0
customer_state        0
dtype: int64

In [ ]:
with engine.connect() as connection:
    df_customer.to_sql("dimcustomer", con=connection, if_exists="append", index=False)

In [140]:
df_seller = pd.read_sql(f"SELECT seller_id,seller_city,seller_state from sellers", conn)

In [141]:
df.head()

,customer_id,customer_unique_id,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,campinas,SP

In [142]:
df.isna().sum()

customer_id           0
customer_unique_id    0
customer_city         0
customer_state        0
dtype: int64

In [ ]:
with engine.connect() as connection:
    df_seller.to_sql("dimseller", con=connection, if_exists="append", index=False)

In [113]:
df_order = pd.read_sql(
"""
SELECT  
    o.order_id,
    o.customer_id,
    SUM(p.payment_value) AS total_payment,        -- مجموع الدفعات
    COUNT(DISTINCT oi.seller_id) AS total_sellers, -- عدد البائعين في الطلب
    COUNT(oi.order_item_id) AS total_items,        -- عدد المنتجات
    o.order_status,
    o.order_purchase_timestamp,
    o.order_approved_at,
    o.order_delivered_carrier_date,
    o.order_delivered_customer_date,
    o.order_estimated_delivery_date
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
JOIN order_payments p ON o.order_id = p.order_id
GROUP BY 
    o.order_id,
    o.customer_id,
    o.order_status,
    o.order_purchase_timestamp,
    o.order_approved_at,
    o.order_delivered_carrier_date,
    o.order_delivered_customer_date,
    o.order_estimated_delivery_date;


 """,   conn,
)

In [114]:
df_order.head()

,order_id,customer_id,total_payment,total_sellers,total_items,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,72.19,1,1,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29 00:00:00
1,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,259.83,1,1,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15 00:00:00
2,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,216.87,1,1,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05 00:00:00
3,00024acbcdf0a6daa1e931b038114c75,d4eb9395c8c0431ee92fce09860c5a06,25.78,1,1,delivered,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20 00:00:00
4,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,218.04,1,1,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17 00:00:00

In [115]:
timedate = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date",
]
df_order [timedate] = df_order [timedate].apply(pd.to_datetime)

In [116]:
df_order [
    (df_order ["order_status"] == "delivered")
    & (df_order [timedate].isna().any(axis=1))
].dropna(inplace=True)

In [117]:
df_order.head()
df_order.info()
df_order.isna().sum()

<class 'pandas.DataFrame'>
RangeIndex: 98665 entries, 0 to 98664
Data columns (total 11 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       98665 non-null  str
 1   customer_id                    98665 non-null  str
 2   total_payment                  98665 non-null  float64
 3   total_sellers                  98665 non-null  int64
 4   total_items                    98665 non-null  int64
 5   order_status                   98665 non-null  str
 6   order_purchase_timestamp       98665 non-null  datetime64[us]
 7   order_approved_at              98651 non-null  datetime64[us]
 8   order_delivered_carrier_date   97656 non-null  datetime64[us]
 9   order_delivered_customer_date  96475 non-null  datetime64[us]
 10  order_estimated_delivery_date  98665 non-null  datetime64[us]
dtypes: datetime64[us](5), float64(1), int64(2), str(3)
memory usage: 8.3 MB

order_id                            0
customer_id                         0
total_payment                       0
total_sellers                       0
total_items                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                  14
order_delivered_carrier_date     1009
order_delivered_customer_date    2190
order_estimated_delivery_date       0
dtype: int64

In [118]:
df_order.isna().sum()

order_id                            0
customer_id                         0
total_payment                       0
total_sellers                       0
total_items                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                  14
order_delivered_carrier_date     1009
order_delivered_customer_date    2190
order_estimated_delivery_date       0
dtype: int64

In [119]:
df_order["purchase_date"] = df_order ["order_purchase_timestamp"].dt.date
df_order ["purchase_time"] = df_order ["order_purchase_timestamp"].dt.time
df_order ["approved_date"] = df_order ["order_approved_at"].dt.date
df_order ["approved_time"] = df_order ["order_approved_at"].dt.time

df_order ["carrier_date"] = df_order ["order_delivered_carrier_date"].dt.date
df_order ["carrier_time"] = df_order ["order_delivered_carrier_date"].dt.time

df_order ["delivered_date"] = df_order ["order_delivered_customer_date"].dt.date
df_order ["delivered_time"] = df_order ["order_delivered_customer_date"].dt.time

df_order ["estimated_date"] = df_order ["order_estimated_delivery_date"].dt.date

In [120]:
df_order.head()

,order_id,customer_id,total_payment,total_sellers,total_items,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,purchase_date,purchase_time,approved_date,approved_time,carrier_date,carrier_time,delivered_date,delivered_time,estimated_date
0,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,72.19,1,1,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29,2017-09-13,08:59:02,2017-09-13,09:45:35,2017-09-19,18:34:16,2017-09-20,23:43:48,2017-09-29
1,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,259.83,1,1,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15,2017-04-26,10:53:06,2017-04-26,11:05:13,2017-05-04,14:35:00,2017-05-12,16:04:24,2017-05-15
2,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,216.87,1,1,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05,2018-01-14,14:33:31,2018-01-14,14:48:30,2018-01-16,12:36:48,2018-01-22,13:19:16,2018-02-05
3,00024acbcdf0a6daa1e931b038114c75,d4eb9395c8c0431ee92fce09860c5a06,25.78,1,1,delivered,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20,2018-08-08,10:00:35,2018-08-08,10:10:18,2018-08-10,13:28:00,2018-08-14,13:32:39,2018-08-20
4,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,218.04,1,1,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17,2017-02-04,13:57:51,2017-02-04,14:10:13,2017-02-16,09:46:09,2017-03-01,16:42:31,2017-03-17

In [121]:
def make_date_key(series):
    return (
        series.astype(str)
        .str.replace("-", "")
        .replace(["NaT", "nan", "None"], "0")
        .fillna("0")
        .astype(int)
    )


def make_time_key(series):
    return (
        series.astype(str)
        .str.replace(":", "")
        .str.replace(".", "")
        .replace(["NaT", "nan", "None"], "0")
        .fillna("0")
        .astype(int)
    )

df_order ["date_purchase_key"] = make_date_key(df_order ["purchase_date"])
df_order ["date_approved_key"] = make_date_key(df_order ["approved_date"])
df_order ["date_delivered_carrier_key"] = make_date_key(df_order ["carrier_date"])
df_order ["date_delivered_customer_key"] = make_date_key(df_order ["delivered_date"])
df_order ["date_estimated_key"] = make_date_key(df_order ["estimated_date"])

df_order ["time_purchase_key"] = make_time_key(df_order ["purchase_time"])
df_order ["time_approved_key"] = make_time_key(df_order ["approved_time"])
df_order ["time_delivered_carrier_key"] = make_time_key(df_order ["carrier_time"])
df_order ["time_delivered_customer_key"] = make_time_key(df_order ["delivered_time"])

In [122]:
df_order.head()

,order_id,customer_id,total_payment,total_sellers,total_items,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,...,estimated_date,date_purchase_key,date_approved_key,date_delivered_carrier_key,date_delivered_customer_key,date_estimated_key,time_purchase_key,time_approved_key,time_delivered_carrier_key,time_delivered_customer_key
0,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,72.19,1,1,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,...,2017-09-29,20170913,20170913,20170919,20170920,20170929,85902,94535,183416,234348
1,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,259.83,1,1,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,...,2017-05-15,20170426,20170426,20170504,20170512,20170515,105306,110513,143500,160424
2,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,216.87,1,1,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,...,2018-02-05,20180114,20180114,20180116,20180122,20180205,143331,144830,123648,131916
3,00024acbcdf0a6daa1e931b038114c75,d4eb9395c8c0431ee92fce09860c5a06,25.78,1,1,delivered,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,...,2018-08-20,20180808,20180808,20180810,20180814,20180820,100035,101018,132800,133239
4,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,218.04,1,1,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,...,2017-03-17,20170204,20170204,20170216,20170301,20170317,135751,141013,94609,164231

In [123]:
df_order.drop_duplicates(inplace=True)

In [124]:
df_order.drop(columns=['order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date','order_estimated_delivery_date','purchase_date'
,'purchase_time'                    
,'approved_date'                    
,'approved_time'                    
,'carrier_date'                   
,'carrier_time'                   
,'delivered_date'                 
,'delivered_time'                 
,'estimated_date'], inplace=True)

In [125]:
df_order.head()

,order_id,customer_id,total_payment,total_sellers,total_items,order_status,date_purchase_key,date_approved_key,date_delivered_carrier_key,date_delivered_customer_key,date_estimated_key,time_purchase_key,time_approved_key,time_delivered_carrier_key,time_delivered_customer_key
0,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,72.19,1,1,delivered,20170913,20170913,20170919,20170920,20170929,85902,94535,183416,234348
1,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,259.83,1,1,delivered,20170426,20170426,20170504,20170512,20170515,105306,110513,143500,160424
2,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,216.87,1,1,delivered,20180114,20180114,20180116,20180122,20180205,143331,144830,123648,131916
3,00024acbcdf0a6daa1e931b038114c75,d4eb9395c8c0431ee92fce09860c5a06,25.78,1,1,delivered,20180808,20180808,20180810,20180814,20180820,100035,101018,132800,133239
4,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,218.04,1,1,delivered,20170204,20170204,20170216,20170301,20170317,135751,141013,94609,164231

In [126]:
df_order.isna().sum()

order_id                       0
customer_id                    0
total_payment                  0
total_sellers                  0
total_items                    0
order_status                   0
date_purchase_key              0
date_approved_key              0
date_delivered_carrier_key     0
date_delivered_customer_key    0
date_estimated_key             0
time_purchase_key              0
time_approved_key              0
time_delivered_carrier_key     0
time_delivered_customer_key    0
dtype: int64

In [127]:
df_order.info()

<class 'pandas.DataFrame'>
RangeIndex: 98665 entries, 0 to 98664
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   order_id                     98665 non-null  str
 1   customer_id                  98665 non-null  str
 2   total_payment                98665 non-null  float64
 3   total_sellers                98665 non-null  int64
 4   total_items                  98665 non-null  int64
 5   order_status                 98665 non-null  str
 6   date_purchase_key            98665 non-null  int64
 7   date_approved_key            98665 non-null  int64
 8   date_delivered_carrier_key   98665 non-null  int64
 9   date_delivered_customer_key  98665 non-null  int64
 10  date_estimated_key           98665 non-null  int64
 11  time_purchase_key            98665 non-null  int64
 12  time_approved_key            98665 non-null  int64
 13  time_delivered_carrier_key   98665 non-null  int64
 14  time_delivered_customer_key  98665 non-null  int64
dtypes: float64(1), int64(11), str(3)
memory usage: 11.3 MB

In [128]:
df_order = df_order.rename(columns={"customer_key":"customer_id",
                        "seller_key":"seller_id"})

In [129]:
df_order.head()

,order_id,customer_id,total_payment,total_sellers,total_items,order_status,date_purchase_key,date_approved_key,date_delivered_carrier_key,date_delivered_customer_key,date_estimated_key,time_purchase_key,time_approved_key,time_delivered_carrier_key,time_delivered_customer_key
0,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,72.19,1,1,delivered,20170913,20170913,20170919,20170920,20170929,85902,94535,183416,234348
1,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,259.83,1,1,delivered,20170426,20170426,20170504,20170512,20170515,105306,110513,143500,160424
2,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,216.87,1,1,delivered,20180114,20180114,20180116,20180122,20180205,143331,144830,123648,131916
3,00024acbcdf0a6daa1e931b038114c75,d4eb9395c8c0431ee92fce09860c5a06,25.78,1,1,delivered,20180808,20180808,20180810,20180814,20180820,100035,101018,132800,133239
4,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,218.04,1,1,delivered,20170204,20170204,20170216,20170301,20170317,135751,141013,94609,164231

In [130]:
def key_to_datetime(series):
    return pd.to_datetime(
        series.replace(0, pd.NA),  # استبدال 0 بـ NA
        format='%Y%m%d',
        errors='coerce'            # أي قيمة غير صالحة تتحول NaT
    )

# تحويل مؤقت للحساب
purchase_dt = key_to_datetime(df_order['date_purchase_key'])
delivered_dt = key_to_datetime(df_order['date_delivered_customer_key'])
estimated_dt = key_to_datetime(df_order['date_estimated_key'])

# إضافة المقاييس الجديدة
df_order['delivery_duration'] = delivered_dt - purchase_dt
df_order['is_late_delivery'] = delivered_dt > estimated_dt

In [131]:
df_order.head()

,order_id,customer_id,total_payment,total_sellers,total_items,order_status,date_purchase_key,date_approved_key,date_delivered_carrier_key,date_delivered_customer_key,date_estimated_key,time_purchase_key,time_approved_key,time_delivered_carrier_key,time_delivered_customer_key,delivery_duration,is_late_delivery
0,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,72.19,1,1,delivered,20170913,20170913,20170919,20170920,20170929,85902,94535,183416,234348,7 days,False
1,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,259.83,1,1,delivered,20170426,20170426,20170504,20170512,20170515,105306,110513,143500,160424,16 days,False
2,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,216.87,1,1,delivered,20180114,20180114,20180116,20180122,20180205,143331,144830,123648,131916,8 days,False
3,00024acbcdf0a6daa1e931b038114c75,d4eb9395c8c0431ee92fce09860c5a06,25.78,1,1,delivered,20180808,20180808,20180810,20180814,20180820,100035,101018,132800,133239,6 days,False
4,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,218.04,1,1,delivered,20170204,20170204,20170216,20170301,20170317,135751,141013,94609,164231,25 days,False

In [136]:
from sqlalchemy import create_engine

engine = create_engine("postgresql://postgres:admin@localhost:5432/new-DWH")
with engine.connect() as connection:
    dim_customer = pd.read_sql("SELECT customer_id, customer_key FROM DimCustomer", con=connection)

In [137]:
# ربط مع DimCustomer
df_order = df_order.merge(dim_customer, on="customer_id", how="left")

# معالجة القيم المفقودة
df_order['customer_key'] = df_order['customer_key'].fillna(0).astype(int)

In [138]:
df_order.head()

,order_id,customer_id,total_payment,total_sellers,total_items,order_status,date_purchase_key,date_approved_key,date_delivered_carrier_key,date_delivered_customer_key,date_estimated_key,time_purchase_key,time_approved_key,time_delivered_carrier_key,time_delivered_customer_key,delivery_duration,is_late_delivery,customer_key_x,customer_key_y,customer_key
0,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,72.19,1,1,delivered,20170913,20170913,20170919,20170920,20170929,85902,94535,183416,234348,7 days,False,65558,65558,65558
1,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,259.83,1,1,delivered,20170426,20170426,20170504,20170512,20170515,105306,110513,143500,160424,16 days,False,34266,34266,34266
2,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,216.87,1,1,delivered,20180114,20180114,20180116,20180122,20180205,143331,144830,123648,131916,8 days,False,34956,34956,34956
3,00024acbcdf0a6daa1e931b038114c75,d4eb9395c8c0431ee92fce09860c5a06,25.78,1,1,delivered,20180808,20180808,20180810,20180814,20180820,100035,101018,132800,133239,6 days,False,51764,51764,51764
4,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,218.04,1,1,delivered,20170204,20170204,20170216,20170301,20170317,135751,141013,94609,164231,25 days,False,7603,7603,7603

In [140]:
# ترتيب الأعمدة وحذف customer_id و seller_id
df_order = df_order[[
    "order_id",
    "customer_key",
    "total_payment",
    "total_sellers",
    "total_items",
    "order_status",
    "date_purchase_key",
    "date_approved_key",
    "date_delivered_carrier_key",
    "date_delivered_customer_key",
    "date_estimated_key",
    "time_purchase_key",
    "time_approved_key",
    "time_delivered_carrier_key",
    "time_delivered_customer_key",
    "delivery_duration",
    "is_late_delivery"
]]

In [108]:
df_order.head()

,order_id,customer_key,seller_key,total_payment,order_status,date_purchase_key,date_approved_key,date_delivered_carrier_key,date_delivered_customer_key,date_estimated_key,time_purchase_key,time_approved_key,time_delivered_carrier_key,time_delivered_customer_key,delivery_duration,is_late_delivery
0,00010242fe8c5a6d1ba2dd792cb16214,65558,514,72.19,delivered,20170913,20170913,20170919,20170920,20170929,85902,94535,183416,234348,7 days,False
1,00018f77f2f0320c557190d7a144bdd3,34266,472,259.83,delivered,20170426,20170426,20170504,20170512,20170515,105306,110513,143500,160424,16 days,False
2,000229ec398224ef6ca0657da4fc703e,34956,1825,216.87,delivered,20180114,20180114,20180116,20180122,20180205,143331,144830,123648,131916,8 days,False
3,00024acbcdf0a6daa1e931b038114c75,51764,2024,25.78,delivered,20180808,20180808,20180810,20180814,20180820,100035,101018,132800,133239,6 days,False
4,00042b26cf59d7ce69dfabb4e55b4fd9,7603,1598,218.04,delivered,20170204,20170204,20170216,20170301,20170317,135751,141013,94609,164231,25 days,False

In [141]:
df_order.info()

<class 'pandas.DataFrame'>
RangeIndex: 98665 entries, 0 to 98664
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   order_id                     98665 non-null  str
 1   customer_key                 98665 non-null  int64
 2   total_payment                98665 non-null  float64
 3   total_sellers                98665 non-null  int64
 4   total_items                  98665 non-null  int64
 5   order_status                 98665 non-null  str
 6   date_purchase_key            98665 non-null  int64
 7   date_approved_key            98665 non-null  int64
 8   date_delivered_carrier_key   98665 non-null  int64
 9   date_delivered_customer_key  98665 non-null  int64
 10  date_estimated_key           98665 non-null  int64
 11  time_purchase_key            98665 non-null  int64
 12  time_approved_key            98665 non-null  int64
 13  time_delivered_carrier_key   98665 non-null  int64
 14  time_delivered_customer_key  98665 non-null  int64
 15  delivery_duration            96475 non-null  timedelta64[us]
 16  is_late_delivery             98665 non-null  bool
dtypes: bool(1), float64(1), int64(12), str(2), timedelta64[us](1)
memory usage: 12.1 MB

In [142]:
df_order['delivery_duration'] = df_order['delivery_duration'].astype(str)

In [143]:
# كشف الصفوف المتكررة بناءً على order_id
duplicates = df_order[df_order.duplicated(subset=['order_id'], keep=False)]

duplicates.info()

<class 'pandas.DataFrame'>
RangeIndex: 0 entries
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   order_id                     0 non-null      str
 1   customer_key                 0 non-null      int64
 2   total_payment                0 non-null      float64
 3   total_sellers                0 non-null      int64
 4   total_items                  0 non-null      int64
 5   order_status                 0 non-null      str
 6   date_purchase_key            0 non-null      int64
 7   date_approved_key            0 non-null      int64
 8   date_delivered_carrier_key   0 non-null      int64
 9   date_delivered_customer_key  0 non-null      int64
 10  date_estimated_key           0 non-null      int64
 11  time_purchase_key            0 non-null      int64
 12  time_approved_key            0 non-null      int64
 13  time_delivered_carrier_key   0 non-null      int64
 14  time_delivered_customer_key  0 non-null      int64
 15  delivery_duration            0 non-null      str
 16  is_late_delivery             0 non-null      bool
dtypes: bool(1), float64(1), int64(12), str(3)
memory usage: 132.0 bytes

In [144]:
df_order = df_order.drop_duplicates(subset=['order_id'])

In [145]:
df_order.info()

<class 'pandas.DataFrame'>
RangeIndex: 98665 entries, 0 to 98664
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   order_id                     98665 non-null  str
 1   customer_key                 98665 non-null  int64
 2   total_payment                98665 non-null  float64
 3   total_sellers                98665 non-null  int64
 4   total_items                  98665 non-null  int64
 5   order_status                 98665 non-null  str
 6   date_purchase_key            98665 non-null  int64
 7   date_approved_key            98665 non-null  int64
 8   date_delivered_carrier_key   98665 non-null  int64
 9   date_delivered_customer_key  98665 non-null  int64
 10  date_estimated_key           98665 non-null  int64
 11  time_purchase_key            98665 non-null  int64
 12  time_approved_key            98665 non-null  int64
 13  time_delivered_carrier_key   98665 non-null  int64
 14  time_delivered_customer_key  98665 non-null  int64
 15  delivery_duration            96475 non-null  str
 16  is_late_delivery             98665 non-null  bool
dtypes: bool(1), float64(1), int64(12), str(3)
memory usage: 12.1 MB

In [ ]:
with engine.connect() as connection:
    df_order.to_sql('factorder', con=connection, if_exists='append', index=False)

: